# Generated by Django 4.1.1 on 2022-09-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
