# Generated by Django 4.1.1 on 2022-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_photography_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photography',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
